use anyhow::Error;

// users.getFullUser
pub async fn get_full_user() -> Result<(), Error> {
    Ok(())
}

// users.getUsers
pub async fn get_users() -> Result<(), Error> {
    Ok(())
}

// contacts.resolvePhone
pub async fn resolve_phone() -> Result<(), Error> {
    Ok(())
}